---
nginx_config_http_template_enable: yes
nginx_config_http_template:
  default:
    template_file: http/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    servers:
      server_ssl:
        listen:
          listen_ssl:
            port: 443
            ssl: yes
        ssl:
          cert: /etc/ssl/certs/azure_chain.pem
          key: /etc/ssl/private/azure_key.pem
        reverse_proxy:
          locations:
            backend:
              location: /
              proxy_pass: http://ingress
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
                header_x_real_ip:
                  name: X-Real-IP
                  value: $remote_addr
                header_x_forwarded_for:
                  name: X-Forwarded-For
                  value: $proxy_add_x_forwarded_for
                header_x_forwarded_proto:
                  name: X-Forwarded-Proto
                  value: $scheme
      server_redirect:
        listen:
          listen_http:
            port: 80
        returns:
          return301:
            location: /
            code: 301
            value: https://$host$request_uri
      server_backup:
        listen:
          listen_backup:
            port: 8080
        reverse_proxy:
          locations:
            backend:
              location: /
              proxy_pass: http://ingress
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
                header_x_real_ip:
                  name: X-Real-IP
                  value: $remote_addr
                header_x_forwarded_for:
                  name: X-Forwarded-For
                  value: $proxy_add_x_forwarded_for
                header_x_forwarded_proto:
                  name: X-Forwarded-Proto
                  value: $scheme
    upstreams:
      ingress:
        name: ingress
        servers: "{{ upstream_servers }}"
